---
version: '3'
services:
  db:
    image: postgres

  redis:
    image: redis

  worker:
    build: .
    command: celery worker --app=app.tasks
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  app:
    build: .
    command: python run.py
    environment:
      FLASK_APP: app
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
      - redis
